clients: backup: list file not found etc/doesnotexist
mount: only root can do that
clients: backup: could not mount nfs share
mount: only root can do that
clients: backup: could not mount smb share
clients: backup: ssh protocol not supported
mount: only root can do that
clients: backup: could not mount smb share
mount: only root can do that
clients: backup: could not mount smb share
mount: only root can do that
clients: backup: could not mount smb share
mount: only root can do that
clients: backup: could not mount smb share
>List 0 client(s):
>List 1 client(s):
-> file://localhost etc/doesnotexist
 -> Reading list file
>List 0 client(s):
>List 1 client(s):
-> nfs://myclient /home/User/devel
>List 2 client(s):
-> nfs://myclient /home/User/devel
-> smb://Myself:flesyM@myclient C:\Backup\Backup.LST
>List 3 client(s):
-> nfs://myclient /home/User/devel
-> smb://Myself:flesyM@myclient C:\Backup\Backup.LST
-> ssh://otherclient c:/home/backup/Backup.list
>List 4 client(s):
-> nfs://myclient /home/User/devel
-> smb://Myself:flesyM@myclient C:\Backup\Backup.LST
-> ssh://otherclient c:/home/backup/Backup.list
-> smb://user@client c:/home/BlaH/Backup.list
>List 5 client(s):
-> nfs://myclient /home/User/devel
-> smb://Myself:flesyM@myclient C:\Backup\Backup.LST
-> ssh://otherclient c:/home/backup/Backup.list
-> smb://user@client c:/home/BlaH/Backup.list
-> smb://user@client c:/home/BlaH/Backup.list
>List 6 client(s):
-> nfs://myclient /home/User/devel
-> smb://Myself:flesyM@myclient C:\Backup\Backup.LST
-> ssh://otherclient c:/home/backup/Backup.list
-> smb://user@client c:/home/BlaH/Backup.list
-> smb://user@client c:/home/BlaH/Backup.list
-> smb://client c:/home/BlaH/Backup.list
>List 7 client(s):
-> nfs://myclient /home/User/devel
-> smb://Myself:flesyM@myclient C:\Backup\Backup.LST
-> ssh://otherclient c:/home/backup/Backup.list
-> smb://user@client c:/home/BlaH/Backup.list
-> smb://user@client c:/home/BlaH/Backup.list
-> smb://client c:/home/BlaH/Backup.list
-> smb://client c:/home/BlaH/Backup.list
Database initialized
 --> Issuing command: mount -t nfs -o ro,nolock myclient:/home/User/devel test_db/mount
 --> Issuing command: mount -t smbfs -o ro,nocase,username=Myself,password=flesyM //myclient/c$ test_db/mount
 --> Issuing command: mount -t smbfs -o ro,nocase,username=user //client/c$ test_db/mount
 --> Issuing command: mount -t smbfs -o ro,nocase,username=user //client/c$ test_db/mount
 --> Issuing command: mount -t smbfs -o ro,nocase //client/c$ test_db/mount
 --> Issuing command: mount -t smbfs -o ro,nocase //client/c$ test_db/mount
Database closed (total contents: 0 file(s))
Database opened (active contents: 0 file(s))
 -> Reading list file
Backup client 'localhost' using protocol 'file'
Backup path 'test'
 -> Building list of files
 -> Parsing list of files
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files
Database closed (total contents: 15 file(s))
Database opened (active contents: 15 file(s))
 -> Reading list file
Backup client 'localhost' using protocol 'file'
Backup path 'test'
 -> Building list of files
 -> Parsing list of files
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files
Database closed (total contents: 15 file(s))
