clients: backup: list file not found etc/doesnotexist
mount: only root can do that
clients: backup: ssh protocol not supported
>List 0 client(s):
 --> Client: localhost
>List 1 client(s):
-> file://localhost etc/doesnotexist
Backup client 'localhost' using protocol 'file'
 -> Reading backup list
>List 0 client(s):
 --> Client: myclient
>List 1 client(s):
-> nfs://myclient /home/User/devel
 --> Client: myclient
>List 2 client(s):
-> nfs://myclient /home/User/devel
-> smb://Myself:flesyM@myclient C:\Backup\Backup.LST
 --> Client: otherclient
>List 3 client(s):
-> nfs://myclient /home/User/devel
-> smb://Myself:flesyM@myclient C:\Backup\Backup.LST
-> ssh://otherclient c:/home/backup/Backup.list
 --> Client: client
>List 4 client(s):
-> nfs://myclient /home/User/devel
-> smb://Myself:flesyM@myclient C:\Backup\Backup.LST
-> ssh://otherclient c:/home/backup/Backup.list
-> smb://user@client c:/home/BlaH/Backup.list
 --> Client: client
>List 5 client(s):
-> nfs://myclient /home/User/devel
-> smb://Myself:flesyM@myclient C:\Backup\Backup.LST
-> ssh://otherclient c:/home/backup/Backup.list
-> smb://user@client c:/home/BlaH/Backup.list
-> smb://user@client c:/home/BlaH/Backup.list
 --> Client: client
>List 6 client(s):
-> nfs://myclient /home/User/devel
-> smb://Myself:flesyM@myclient C:\Backup\Backup.LST
-> ssh://otherclient c:/home/backup/Backup.list
-> smb://user@client c:/home/BlaH/Backup.list
-> smb://user@client c:/home/BlaH/Backup.list
-> smb://client c:/home/BlaH/Backup.list
 --> Client: client
>List 7 client(s):
-> nfs://myclient /home/User/devel
-> smb://Myself:flesyM@myclient C:\Backup\Backup.LST
-> ssh://otherclient c:/home/backup/Backup.list
-> smb://user@client c:/home/BlaH/Backup.list
-> smb://user@client c:/home/BlaH/Backup.list
-> smb://client c:/home/BlaH/Backup.list
-> smb://client c:/home/BlaH/Backup.list
Database initialized
Client unreachable 'myclient' using protocol 'nfs'
Client unreachable 'myclient' using protocol 'smb'
Client unreachable 'otherclient' using protocol 'ssh'
Client unreachable 'client' using protocol 'smb'
Client unreachable 'client' using protocol 'smb'
Client unreachable 'client' using protocol 'smb'
Client unreachable 'client' using protocol 'smb'
Database closed (total contents: 0 file(s))
 --> Client: localhost
Database opened (active contents: 0 file(s))
Backup client 'localhost' using protocol 'file'
 -> Reading backup list
 --> Path: test
 --> Path: test2//
Backup path 'test'
 -> Building list of files
 -> Parsing list of files
 --> Files to add: 11 (0 bytes)
                  --> No files to remove
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files
 --> Files to add: 5 (928768 bytes)
                  --> Copied: 15%                  --> Copied: 43%                  --> Copied: 100%                  --> No files to remove
Database closed (total contents: 16 file(s))
 --> Client: localhost
Database opened (active contents: 16 file(s))
Backup client 'localhost' using protocol 'file'
 -> Reading backup list
 --> Path: test
 --> Path: test2//
Backup path 'test'
 -> Building list of files
 -> Parsing list of files
 --> No files to add
 --> No files to remove
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files
 --> No files to add
 --> No files to remove
Database closed (total contents: 16 file(s))
