Tools Test

Test: zcopy (and thus getchecksum)
In: 10485760 bytes, checksum: f1c9645dbc14efddc7d8a322685f26eb
Out: 10208 bytes, checksum: b7350db49d036137b2ef752a82145e91

Test: testdir
Check test_db dir: 0
Check but do not create test_db/0 1 dir: 1
Check and create test_db/0 1 dir: 1
Check test_db/0 1 dir: 0

Test: testfile
Check but do not create test_db/0 1/a b file: 1
Check and create test_db/0 1/a b file: 1
Check test_db/0 1/a b file: 0

Test: type_letter
File   : f
Dir    : d
Char   : c
Block  : b
FIFO   : p
Link   : l
Socket : s
Unknown: ?

Test: type_mode
File   : 0100000
Dir    : 0040000
Char   : 0020000
Block  : 0060000
FIFO   : 0010000
Link   : 0120000
Socket : 0140000
Unknown: 0000000

Test: params_readline
Read 0 parameters from : '' '' ''
Read 0 parameters from # Normal comment: '' '' ''
Read 0 parameters from  	# Displaced comment: '' '' ''
Read 1 parameters from 	key # Comment: 'key' '' ''
Read 2 parameters from key	 "string" # Comment: 'key' '' 'string'
Read 3 parameters from key 	type	"string" # Comment: 'key' 'type' 'string'
Read 2 parameters from key	 string 	# Comment: 'key' '' 'string'
Read 3 parameters from key 	type	 string # Comment: 'key' 'type' 'string'
Read -1 parameters from key 	type 	"string # Comment: 'key' '' '"string'
Read -1 parameters from key 	type string" # Comment: 'key' '' ''
Read 2 parameters from key	 "this is	a 	string" # Comment: 'key' '' 'this is	a 	string'
Read 3 parameters from key 	type	 "this is	a 	string" # Comment: 'key' 'type' 'this is	a 	string'

metadata_get
 * type: 0x00008000
 * size: 13
 * mtime: 2006-10-22  0:00:00
 * uid: 1000
 * gid: 1000
 * mode: 0x000001a4
