Fill in list
List 1 element(s):
test/testfile
List 2 element(s):
test
test/testfile
List 3 element(s):
test
test/subdir/testfile1
test/testfile
List 4 element(s):
test
test/subdir
test/subdir/testfile1
test/testfile
List 5 element(s):
test
test/subdir
test/subdir/testfile1
test/testfile
test/testfile
Empty list
List 4 element(s):
test/subdir
test/subdir/testfile1
test/testfile
test/testfile
List 3 element(s):
test/subdir
test/subdir/testfile1
test/testfile
List 2 element(s):
test/subdir
test/testfile
List 1 element(s):
test/testfile
List 0 element(s):
