#!/bin/sh

# From test_setup
TESTDIRCIFS="$PWD/test_cifs"
TESTDIRNFS="$PWD/test_nfs"
ROOTDIRNFS="/home/User"

# Expect -t
case "$1" in
"-t" )
  echo > /dev/null
  ;;
* )
  exit -EINVAL
  ;;
esac
shift

# Get type
fstype=$1
shift

# Skip options
if [ "$1" == "-o" ]; then
  shift
  shift
fi

# Expect source
case "$fstype" in
"cifs" )
  src="$TESTDIRCIFS"
  ;;
"nfs" )
  src="$TESTDIRNFS`echo $1 | sed "s%.*$ROOTDIRNFS%%"`"
  ;;
* )
  exit -EINVAL
  ;;
esac
shift

# Get destination
dest="$1"
shift

# Simulate mounting of share
rm -rf "$dest"
ln -sf "$src" "$dest"

# Success
exit 0
