Failed to create directory: test_db/data/fe/te/st4
Failed to create directory: test_db/data/fe/dc/76/test5
Tools Test

Test: zcopy (and thus getchecksum)
In: 10485760 bytes, checksum: f1c9645dbc14efddc7d8a322685f26eb
Out: 10208 bytes, checksum: b7350db49d036137b2ef752a82145e91

Test: testdir
Check test_db dir: 0
Check but do not create test_db/0 1 dir: 1
Check and create test_db/0 1 dir: 1
Check test_db/0 1 dir: 0

Test: testfile
Check but do not create test_db/0 1/a b file: 1
Check and create test_db/0 1/a b file: 1
Check test_db/0 1/a b file: 0

Test: type_letter
File   : f
Dir    : d
Char   : c
Block  : b
FIFO   : p
Link   : l
Socket : s
Unknown: ?

Test: type_mode
File   : 0100000
Dir    : 0040000
Char   : 0020000
Block  : 0060000
FIFO   : 0010000
Link   : 0120000
Socket : 0140000
Unknown: 0000000

Test: getdir
Check test_db/data dir: 1
febatest1 status: 0, path: test_db/data/fe/ba/test1
fe98test2 status: 0, path: test_db/data/fe/98/test2
fe98test3 status: 1, path: test_db/data/fe/98/test3
fetest4 status: 2, path: test_db/data/fe/te/st4
fedc76test5 status: 2, path: test_db/data/fe/dc/76/test5
fedc76test6 status: 1, path: test_db/data/fe/dc/76/test6
fedc76test6 status: 0, path: test_db/data/fe/dc/76/test6

Test: params_readline
Read 0 parameters from : '' '' ''
Read 0 parameters from # Normal comment: '' '' ''
Read 0 parameters from  	# Displaced comment: '' '' ''
Read 1 parameters from 	key # Comment: 'key' '' ''
Read 2 parameters from key	 "string" # Comment: 'key' '' 'string'
Read 3 parameters from key 	type	"string" # Comment: 'key' 'type' 'string'
Read 2 parameters from key	 string 	# Comment: 'key' '' 'string'
Read 3 parameters from key 	type	 string # Comment: 'key' 'type' 'string'
Read -1 parameters from key 	type 	"string # Comment: 'key' '' '"string'
Read -1 parameters from key 	type string" # Comment: 'key' '' ''
Read 2 parameters from key	 "this is	a 	string" # Comment: 'key' '' 'this is	a 	string'
Read 3 parameters from key 	type	 "this is	a 	string" # Comment: 'key' 'type' 'this is	a 	string'
