clients: backup: list file not found etc/doesnotexist
clients: backup: keyword not implemented in list file etc/localhost.list, line 3
mount: only root can do that
clients: backup: could not mount smb share
clients: backup: ssh protocol not supported
clients: backup: keyword not implemented in list file etc/localhost.list, line 3
List 0 elements:
List 1 elements:
 file://localhost etc/doesnotexist
List 0 elements:
List 1 elements:
 file://localhost etc/localhost.list
List 2 elements:
 file://localhost etc/localhost.list
 smb://Myself:flesyM@myclient C:\Backup\Backup.LST
List 3 elements:
 file://localhost etc/localhost.list
 smb://Myself:flesyM@myclient C:\Backup\Backup.LST
 ssh://otherclient /home/backup/Backup.list
 -> Initialized database list
Backup client 'localhost' using protocol 'file'
Backup path 'test'
 -> Building list of files
 -> Parsing list of files
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files
 -> Saving database list: 16 file(s)
 -> Loaded database list: 16 file(s)
Backup client 'localhost' using protocol 'file'
Backup path 'test'
 -> Building list of files
 -> Parsing list of files
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files
 -> Saving database list: 16 file(s)
