cvs parser: file check: not initialised
test is not under CVS control
-> dirbad
-> dirutd
-> filemod.o
-> filenew.c
-> fileutd.h
test/cvs/nofile is not under CVS control
test/cvs/fileoth is not under CVS control
test/cvs/diroth is not under CVS control
-> fileutd
test/cvs/dirutd/fileoth is not under CVS control
test/cvs/dirbad is not under CVS control
-> dirbad
-> dirutd
-> filemod.o
-> filenew.c
-> fileutd.h
test/cvs/fileutd is not under CVS control
test/cvs/fileoth is not under CVS control
test/cvs/diroth is not under CVS control
