iterate_directory
 --> Dir: 
 --> Dir: cvs/
 --> Dir: cvs/CVS/
 --> Dir: cvs/dirbad/
 --> Dir: cvs/diroth/
 --> Dir: cvs/dirutd/
 --> Dir: cvs/dirutd/CVS/
 --> Dir: testdir/
 --> Dir: subdir/
List 24 elements:
 cvs
 cvs/CVS
 cvs/CVS/Entries
 cvs/dirbad
 cvs/dirbad/fileoth
 cvs/dirbad/fileutd
 cvs/diroth
 cvs/dirutd
 cvs/dirutd/CVS
 cvs/dirutd/CVS/Entries
 cvs/dirutd/fileoth
 cvs/dirutd/fileutd
 cvs/filemod.o
 cvs/filenew.c
 cvs/fileoth
 cvs/fileutd.h
 subdir
 subdir/testfile
 subdir/testfile1
 subdir/testfile2
 testdir
 testfile
 testfile~
 testlink
as previous with subdir in ignore list
 --> Dir: 
 --> Dir: cvs/
 --> Dir: cvs/CVS/
 --> Dir: cvs/dirbad/
 --> Dir: cvs/diroth/
 --> Dir: cvs/dirutd/
 --> Dir: cvs/dirutd/CVS/
 --> Dir: testdir/
List 20 elements:
 cvs
 cvs/CVS
 cvs/CVS/Entries
 cvs/dirbad
 cvs/dirbad/fileoth
 cvs/dirbad/fileutd
 cvs/diroth
 cvs/dirutd
 cvs/dirutd/CVS
 cvs/dirutd/CVS/Entries
 cvs/dirutd/fileoth
 cvs/dirutd/fileutd
 cvs/filemod.o
 cvs/filenew.c
 cvs/fileoth
 cvs/fileutd.h
 testdir
 testfile
 testfile~
 testlink
as previous with testlink in ignore list
 --> Dir: 
 --> Dir: cvs/
 --> Dir: cvs/CVS/
 --> Dir: cvs/dirbad/
 --> Dir: cvs/diroth/
 --> Dir: cvs/dirutd/
 --> Dir: cvs/dirutd/CVS/
 --> Dir: testdir/
List 19 elements:
 cvs
 cvs/CVS
 cvs/CVS/Entries
 cvs/dirbad
 cvs/dirbad/fileoth
 cvs/dirbad/fileutd
 cvs/diroth
 cvs/dirutd
 cvs/dirutd/CVS
 cvs/dirutd/CVS/Entries
 cvs/dirutd/fileoth
 cvs/dirutd/fileutd
 cvs/filemod.o
 cvs/filenew.c
 cvs/fileoth
 cvs/fileutd.h
 testdir
 testfile
 testfile~
as previous with CVS parser
 --> Dir: 
 --> Dir: cvs/
 --> Dir: cvs/dirbad/
 --> Dir: cvs/dirutd/
 --> Dir: testdir/
List 10 elements:
 cvs
 cvs/dirbad
 cvs/dirutd
 cvs/dirutd/fileutd
 cvs/filemod.o
 cvs/filenew.c
 cvs/fileutd.h
 testdir
 testfile
 testfile~
file_list_new, as previous
 --> Dir: 
 --> Dir: cvs/
 --> Dir: cvs/dirbad/
 --> Dir: cvs/dirutd/
 --> Dir: testdir/
List 10 elements:
 cvs
 cvs/dirbad
 cvs/dirutd
 cvs/dirutd/fileutd
 cvs/filemod.o
 cvs/filenew.c
 cvs/fileutd.h
 testdir
 testfile
 testfile~
file_list_new, as previous with ending slash
 --> Dir: 
 --> Dir: cvs/
 --> Dir: cvs/dirbad/
 --> Dir: cvs/dirutd/
 --> Dir: testdir/
List 10 elements:
 cvs
 cvs/dirbad
 cvs/dirutd
 cvs/dirutd/fileutd
 cvs/filemod.o
 cvs/filenew.c
 cvs/fileutd.h
 testdir
 testfile
 testfile~
