>List 0 client(s):
 --> Client: localhost
>List 1 client(s):
Client: localhost
-> file://localhost etc/doesnotexist
Backup client 'localhost' using protocol 'file'
List file not found etc/doesnotexist
>List 0 client(s):
 --> Client: myClient
>List 1 client(s):
Client: myClient
-> nfs://myClient /home/User/hbackup.list
 --> Client: myClient2
>List 2 client(s):
Client: myClient
-> nfs://myClient /home/User/hbackup.list
Client: myClient2
-> smb://myClient C:/Backup/Backup.LST
Options: username=Myself password=flesyM
 --> Client: otherClient
>List 3 client(s):
Client: myClient
-> nfs://myClient /home/User/hbackup.list
Client: myClient2
-> smb://myClient C:/Backup/Backup.LST
Options: username=Myself password=flesyM
Client: otherClient
-> ssh://otherClient c:/home/backup/Backup.list
 --> Client: Client
>List 4 client(s):
Client: myClient
-> nfs://myClient /home/User/hbackup.list
Client: myClient2
-> smb://myClient C:/Backup/Backup.LST
Options: username=Myself password=flesyM
Client: otherClient
-> ssh://otherClient c:/home/backup/Backup.list
Client: Client
-> smb://Client c:/home/BlaH/Backup.list
Options: username=user iocharset=utf8
 --> Client: Client2
>List 5 client(s):
Client: myClient
-> nfs://myClient /home/User/hbackup.list
Client: myClient2
-> smb://myClient C:/Backup/Backup.LST
Options: username=Myself password=flesyM
Client: otherClient
-> ssh://otherClient c:/home/backup/Backup.list
Client: Client
-> smb://Client c:/home/BlaH/Backup.list
Options: username=user iocharset=utf8
Client: Client2
-> smb://Client c:/home/BlaH/Backup.list
Options: nocase username=user password=
 --> Client: Client3
>List 6 client(s):
Client: myClient
-> nfs://myClient /home/User/hbackup.list
Client: myClient2
-> smb://myClient C:/Backup/Backup.LST
Options: username=Myself password=flesyM
Client: otherClient
-> ssh://otherClient c:/home/backup/Backup.list
Client: Client
-> smb://Client c:/home/BlaH/Backup.list
Options: username=user iocharset=utf8
Client: Client2
-> smb://Client c:/home/BlaH/Backup.list
Options: nocase username=user password=
Client: Client3
-> smb://Client c:/home/BlaH/Backup.list
Options: username=
 --> Client: Client4
>List 7 client(s):
Client: myClient
-> nfs://myClient /home/User/hbackup.list
Client: myClient2
-> smb://myClient C:/Backup/Backup.LST
Options: username=Myself password=flesyM
Client: otherClient
-> ssh://otherClient c:/home/backup/Backup.list
Client: Client
-> smb://Client c:/home/BlaH/Backup.list
Options: username=user iocharset=utf8
Client: Client2
-> smb://Client c:/home/BlaH/Backup.list
Options: nocase username=user password=
Client: Client3
-> smb://Client c:/home/BlaH/Backup.list
Options: username=
Client: Client4
-> smb://Client c:/home/BlaH/Backup.list
Options: username= password=
 --> Database initialized
 --> Database active items part open (contents: 0 files)
Client unreachable 'myClient' using protocol 'nfs' (Connection timed out)
Backup client 'myClient2' using protocol 'smb'
 -> Reading backup list file
 --> Path: C:/Test
Backup path 'C:/Test'
 -> Building list of files
 -> Parsing list of files (1)
 --> Files to add: 1 (0 bytes)
 --> Done: 1/1
 --> Files to remove: 0
Unmounted test_db/mount
Protocol not supported: ssh
Backup client 'Client' using protocol 'smb'
List file not found test_db/mount/home/BlaH/Backup.list
Unmounted test_db/mount
Backup client 'Client2' using protocol 'smb'
List file not found test_db/mount/home/BlaH/Backup.list
Unmounted test_db/mount
Backup client 'Client3' using protocol 'smb'
List file not found test_db/mount/home/BlaH/Backup.list
Unmounted test_db/mount
Backup client 'Client4' using protocol 'smb'
List file not found test_db/mount/home/BlaH/Backup.list
Unmounted test_db/mount
 --> Database active items part closed (contents: 1 file)
 --> Client: testhost
>List 1 client(s):
Client: testhost
-> file://localhost etc/localhost.list
 --> Database active items part open (contents: 1 file)
Backup client 'testhost' using protocol 'file'
 -> Reading backup list file
 --> Path: test
 --> Path: test2
Backup path 'test'
 -> Building list of files
Directory should be under CVS control: test/cvs/dirbad
 -> Parsing list of files (13)
 --> Files to add: 13 (0 bytes)
 --> Done: 1/13 --> Done: 2/13 --> Done: 3/13 --> Done: 4/13 --> Done: 5/13 --> Done: 6/13 --> Done: 7/13 --> Done: 8/13 --> Done: 9/13 --> Done: 10/13 --> Done: 11/13 --> Done: 12/13 --> Done: 13/13
 --> Files to remove: 0
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files (5)
 --> Files to add: 5 (928768 bytes)
 --> Done: 1/5 (0.0%) --> Done: 2/5 (15.7%) --> Done: 3/5 (43.6%) --> Done: 4/5 (100.0%) --> Done: 5/5 (100.0%)
 --> Files to remove: 0
 --> Database active items part closed (contents: 19 files)
 --> Client: testhost
>List 1 client(s):
Client: testhost
-> file://testhost etc/localhost.list
 --> Database active items part open (contents: 19 files)
Backup client 'testhost' using protocol 'file'
 -> Reading backup list file
 --> Path: test
 --> Path: test2
Backup path 'test'
 -> Building list of files
Directory should be under CVS control: test/cvs/dirbad
 -> Parsing list of files (13)
 --> Files to add: 0
 --> Files to remove: 0
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files (5)
 --> Files to add: 0
 --> Files to remove: 0
 --> Database active items part closed (contents: 19 files)
