test is not under CVS control
List: 5 file(s)
-> filenew.c
-> filemod.o
-> fileutd.h
-> dirbad
-> dirutd
test/cvs/nofile is not under CVS control
test/cvs/fileoth is not under CVS control
test/cvs/diroth is not under CVS control
test/cvs/CVS is not under CVS control
Directory should be under CVS control: test/cvs/diroth
List: 1 file(s)
-> fileutd
test/cvs/dirutd/fileoth is not under CVS control
test/cvs/dirbad is not under CVS control
test/cvs/CVS is not under CVS control
