>List 28 file(s):
cvs	d	0	0	1000	1000	755	
cvs/CVS	d	0	0	1000	1000	755	
cvs/CVS/Entries	f	141	1	1000	1000	644	
cvs/dirbad	d	0	0	1000	1000	755	
cvs/dirbad/fileoth	f	0	1	1000	1000	644	
cvs/dirbad/fileutd	f	0	1	1000	1000	644	
cvs/diroth	d	0	0	1000	1000	755	
cvs/dirutd	d	0	0	1000	1000	755	
cvs/dirutd/CVS	d	0	0	1000	1000	755	
cvs/dirutd/CVS/Entries	f	42	1	1000	1000	644	
cvs/dirutd/fileoth	f	0	1	1000	1000	644	
cvs/dirutd/fileutd	f	0	1	1000	1000	644	
cvs/filemod.o	f	0	1	1000	1000	644	
cvs/filenew.c	f	0	1	1000	1000	644	
cvs/fileoth	f	0	1	1000	1000	644	
cvs/fileutd.h	f	0	1	1000	1000	644	
dir space	d	0	0	1000	1000	755	
dir space/file space	f	0	1	1000	1000	644	
subdir	d	0	0	1000	1000	755	
subdir/testfile	f	12	1	1000	1000	644	
subdir/testfile1	f	0	1	1000	1000	644	
subdir/testfile2	f	12	1	1000	1000	644	
test space	f	0	1	1000	1000	644	
testdir	d	0	0	1000	1000	755	
testfile	f	13	1	1000	1000	644	
testfile~	f	0	1	1000	1000	644	
testlink	l	8	1	1000	1000	777	testfile
testpipe	p	0	1	1000	1000	644	
as previous with subdir in ignore list
>List 24 file(s):
cvs	d	0	0	1000	1000	755	
cvs/CVS	d	0	0	1000	1000	755	
cvs/CVS/Entries	f	141	1	1000	1000	644	
cvs/dirbad	d	0	0	1000	1000	755	
cvs/dirbad/fileoth	f	0	1	1000	1000	644	
cvs/dirbad/fileutd	f	0	1	1000	1000	644	
cvs/diroth	d	0	0	1000	1000	755	
cvs/dirutd	d	0	0	1000	1000	755	
cvs/dirutd/CVS	d	0	0	1000	1000	755	
cvs/dirutd/CVS/Entries	f	42	1	1000	1000	644	
cvs/dirutd/fileoth	f	0	1	1000	1000	644	
cvs/dirutd/fileutd	f	0	1	1000	1000	644	
cvs/filemod.o	f	0	1	1000	1000	644	
cvs/filenew.c	f	0	1	1000	1000	644	
cvs/fileoth	f	0	1	1000	1000	644	
cvs/fileutd.h	f	0	1	1000	1000	644	
dir space	d	0	0	1000	1000	755	
dir space/file space	f	0	1	1000	1000	644	
test space	f	0	1	1000	1000	644	
testdir	d	0	0	1000	1000	755	
testfile	f	13	1	1000	1000	644	
testfile~	f	0	1	1000	1000	644	
testlink	l	8	1	1000	1000	777	testfile
testpipe	p	0	1	1000	1000	644	
as previous with testlink in ignore list
>List 23 file(s):
cvs	d	0	0	1000	1000	755	
cvs/CVS	d	0	0	1000	1000	755	
cvs/CVS/Entries	f	141	1	1000	1000	644	
cvs/dirbad	d	0	0	1000	1000	755	
cvs/dirbad/fileoth	f	0	1	1000	1000	644	
cvs/dirbad/fileutd	f	0	1	1000	1000	644	
cvs/diroth	d	0	0	1000	1000	755	
cvs/dirutd	d	0	0	1000	1000	755	
cvs/dirutd/CVS	d	0	0	1000	1000	755	
cvs/dirutd/CVS/Entries	f	42	1	1000	1000	644	
cvs/dirutd/fileoth	f	0	1	1000	1000	644	
cvs/dirutd/fileutd	f	0	1	1000	1000	644	
cvs/filemod.o	f	0	1	1000	1000	644	
cvs/filenew.c	f	0	1	1000	1000	644	
cvs/fileoth	f	0	1	1000	1000	644	
cvs/fileutd.h	f	0	1	1000	1000	644	
dir space	d	0	0	1000	1000	755	
dir space/file space	f	0	1	1000	1000	644	
test space	f	0	1	1000	1000	644	
testdir	d	0	0	1000	1000	755	
testfile	f	13	1	1000	1000	644	
testfile~	f	0	1	1000	1000	644	
testpipe	p	0	1	1000	1000	644	
as previous with CVS parser
Directory should be under CVS control: test1/cvs/dirbad
>List 18 file(s):
cvs	d	0	0	1000	1000	755	
cvs/CVS	d	0	0	1000	1000	755	
cvs/CVS/Entries	f	141	1	1000	1000	644	
cvs/dirbad	d	0	0	1000	1000	755	
cvs/dirutd	d	0	0	1000	1000	755	
cvs/dirutd/CVS	d	0	0	1000	1000	755	
cvs/dirutd/CVS/Entries	f	42	1	1000	1000	644	
cvs/dirutd/fileutd	f	0	1	1000	1000	644	
cvs/filemod.o	f	0	1	1000	1000	644	
cvs/filenew.c	f	0	1	1000	1000	644	
cvs/fileutd.h	f	0	1	1000	1000	644	
dir space	d	0	0	1000	1000	755	
dir space/file space	f	0	1	1000	1000	644	
test space	f	0	1	1000	1000	644	
testdir	d	0	0	1000	1000	755	
testfile	f	13	1	1000	1000	644	
testfile~	f	0	1	1000	1000	644	
testpipe	p	0	1	1000	1000	644	
as previous
Directory should be under CVS control: test1/cvs/dirbad
>List 18 file(s):
cvs	d	0	0	1000	1000	755	
cvs/CVS	d	0	0	1000	1000	755	
cvs/CVS/Entries	f	141	1	1000	1000	644	
cvs/dirbad	d	0	0	1000	1000	755	
cvs/dirutd	d	0	0	1000	1000	755	
cvs/dirutd/CVS	d	0	0	1000	1000	755	
cvs/dirutd/CVS/Entries	f	42	1	1000	1000	644	
cvs/dirutd/fileutd	f	0	1	1000	1000	644	
cvs/filemod.o	f	0	1	1000	1000	644	
cvs/filenew.c	f	0	1	1000	1000	644	
cvs/fileutd.h	f	0	1	1000	1000	644	
dir space	d	0	0	1000	1000	755	
dir space/file space	f	0	1	1000	1000	644	
test space	f	0	1	1000	1000	644	
testdir	d	0	0	1000	1000	755	
testfile	f	13	1	1000	1000	644	
testfile~	f	0	1	1000	1000	644	
testpipe	p	0	1	1000	1000	644	
 --> Database initialized
 --> Database active items part open (contents: 0 files)
Active list:  0 element(s):
Removed list: 0 element(s):

New classes test
 ---> New: cvs
 ---> New: cvs/CVS
 ---> New: cvs/CVS/Entries
 ---> New: cvs/dirbad
 ---> New: cvs/dirbad/fileoth
 ---> New: cvs/dirbad/fileutd
 ---> New: cvs/diroth
 ---> New: cvs/dirutd
 ---> New: cvs/dirutd/CVS
 ---> New: cvs/dirutd/CVS/Entries
 ---> New: cvs/dirutd/fileoth
 ---> New: cvs/dirutd/fileutd
 ---> New: cvs/filemod.o
 ---> New: cvs/filenew.c
 ---> New: cvs/fileoth
 ---> New: cvs/fileutd.h
 ---> New: dir space
 ---> New: dir space/file space
 ---> New: subdir
 ---> New: subdir/testfile
 ---> New: subdir/testfile1
 ---> New: subdir/testfile2
 ---> New: test space
 ---> New: testdir
 ---> New: testfile
 ---> New: testfile~
 ---> New: testlink
 ---> New: testpipe
Active list:  28 element(s):
file://localhost	/home/User/cvs	d	0	0	1000	1000	755			1	0	
file://localhost	/home/User/cvs/CVS	d	0	0	1000	1000	755			2	0	
file://localhost	/home/User/cvs/CVS/Entries	f	141	1	1000	1000	644			3	0	
file://localhost	/home/User/cvs/dirbad	d	0	0	1000	1000	755			4	0	
file://localhost	/home/User/cvs/dirbad/fileoth	f	0	1	1000	1000	644			5	0	
file://localhost	/home/User/cvs/dirbad/fileutd	f	0	1	1000	1000	644			6	0	
file://localhost	/home/User/cvs/diroth	d	0	0	1000	1000	755			7	0	
file://localhost	/home/User/cvs/dirutd	d	0	0	1000	1000	755			8	0	
file://localhost	/home/User/cvs/dirutd/CVS	d	0	0	1000	1000	755			9	0	
file://localhost	/home/User/cvs/dirutd/CVS/Entries	f	42	1	1000	1000	644			10	0	
file://localhost	/home/User/cvs/dirutd/fileoth	f	0	1	1000	1000	644			11	0	
file://localhost	/home/User/cvs/dirutd/fileutd	f	0	1	1000	1000	644			12	0	
file://localhost	/home/User/cvs/filemod.o	f	0	1	1000	1000	644			13	0	
file://localhost	/home/User/cvs/filenew.c	f	0	1	1000	1000	644			14	0	
file://localhost	/home/User/cvs/fileoth	f	0	1	1000	1000	644			15	0	
file://localhost	/home/User/cvs/fileutd.h	f	0	1	1000	1000	644			16	0	
file://localhost	/home/User/dir space	d	0	0	1000	1000	755			17	0	
file://localhost	/home/User/dir space/file space	f	0	1	1000	1000	644			18	0	
file://localhost	/home/User/subdir	d	0	0	1000	1000	755			19	0	
file://localhost	/home/User/subdir/testfile	f	12	1	1000	1000	644			20	0	
file://localhost	/home/User/subdir/testfile1	f	0	1	1000	1000	644			21	0	
file://localhost	/home/User/subdir/testfile2	f	12	1	1000	1000	644			22	0	
file://localhost	/home/User/test space	f	0	1	1000	1000	644			23	0	
file://localhost	/home/User/testdir	d	0	0	1000	1000	755			24	0	
file://localhost	/home/User/testfile	f	13	1	1000	1000	644			25	0	
file://localhost	/home/User/testfile~	f	0	1	1000	1000	644			26	0	
file://localhost	/home/User/testlink	l	8	0	1000	1000	777	testfile		27	0	
file://localhost	/home/User/testpipe	p	0	1	1000	1000	644			28	0	
Removed list: 0 element(s):
as previous with subdir in ignore list
 ---> Removed: subdir
Active list:  24 element(s):
file://localhost	/home/User/cvs	d	0	0	1000	1000	755			1	0	
file://localhost	/home/User/cvs/CVS	d	0	0	1000	1000	755			2	0	
file://localhost	/home/User/cvs/CVS/Entries	f	141	1	1000	1000	644			3	0	
file://localhost	/home/User/cvs/dirbad	d	0	0	1000	1000	755			4	0	
file://localhost	/home/User/cvs/dirbad/fileoth	f	0	1	1000	1000	644			5	0	
file://localhost	/home/User/cvs/dirbad/fileutd	f	0	1	1000	1000	644			6	0	
file://localhost	/home/User/cvs/diroth	d	0	0	1000	1000	755			7	0	
file://localhost	/home/User/cvs/dirutd	d	0	0	1000	1000	755			8	0	
file://localhost	/home/User/cvs/dirutd/CVS	d	0	0	1000	1000	755			9	0	
file://localhost	/home/User/cvs/dirutd/CVS/Entries	f	42	1	1000	1000	644			10	0	
file://localhost	/home/User/cvs/dirutd/fileoth	f	0	1	1000	1000	644			11	0	
file://localhost	/home/User/cvs/dirutd/fileutd	f	0	1	1000	1000	644			12	0	
file://localhost	/home/User/cvs/filemod.o	f	0	1	1000	1000	644			13	0	
file://localhost	/home/User/cvs/filenew.c	f	0	1	1000	1000	644			14	0	
file://localhost	/home/User/cvs/fileoth	f	0	1	1000	1000	644			15	0	
file://localhost	/home/User/cvs/fileutd.h	f	0	1	1000	1000	644			16	0	
file://localhost	/home/User/dir space	d	0	0	1000	1000	755			17	0	
file://localhost	/home/User/dir space/file space	f	0	1	1000	1000	644			18	0	
file://localhost	/home/User/test space	f	0	1	1000	1000	644			23	0	
file://localhost	/home/User/testdir	d	0	0	1000	1000	755			24	0	
file://localhost	/home/User/testfile	f	13	1	1000	1000	644			25	0	
file://localhost	/home/User/testfile~	f	0	1	1000	1000	644			26	0	
file://localhost	/home/User/testlink	l	8	0	1000	1000	777	testfile		27	0	
file://localhost	/home/User/testpipe	p	0	1	1000	1000	644			28	0	
Removed list: 4 element(s):
file://localhost	/home/User/subdir	d	0	0	1000	1000	755			19	29	
file://localhost	/home/User/subdir/testfile	f	12	1	1000	1000	644			20	30	
file://localhost	/home/User/subdir/testfile1	f	0	1	1000	1000	644			21	31	
file://localhost	/home/User/subdir/testfile2	f	12	1	1000	1000	644			22	32	
as previous with testlink in ignore list
 ---> Removed: testlink
Active list:  23 element(s):
file://localhost	/home/User/cvs	d	0	0	1000	1000	755			1	0	
file://localhost	/home/User/cvs/CVS	d	0	0	1000	1000	755			2	0	
file://localhost	/home/User/cvs/CVS/Entries	f	141	1	1000	1000	644			3	0	
file://localhost	/home/User/cvs/dirbad	d	0	0	1000	1000	755			4	0	
file://localhost	/home/User/cvs/dirbad/fileoth	f	0	1	1000	1000	644			5	0	
file://localhost	/home/User/cvs/dirbad/fileutd	f	0	1	1000	1000	644			6	0	
file://localhost	/home/User/cvs/diroth	d	0	0	1000	1000	755			7	0	
file://localhost	/home/User/cvs/dirutd	d	0	0	1000	1000	755			8	0	
file://localhost	/home/User/cvs/dirutd/CVS	d	0	0	1000	1000	755			9	0	
file://localhost	/home/User/cvs/dirutd/CVS/Entries	f	42	1	1000	1000	644			10	0	
file://localhost	/home/User/cvs/dirutd/fileoth	f	0	1	1000	1000	644			11	0	
file://localhost	/home/User/cvs/dirutd/fileutd	f	0	1	1000	1000	644			12	0	
file://localhost	/home/User/cvs/filemod.o	f	0	1	1000	1000	644			13	0	
file://localhost	/home/User/cvs/filenew.c	f	0	1	1000	1000	644			14	0	
file://localhost	/home/User/cvs/fileoth	f	0	1	1000	1000	644			15	0	
file://localhost	/home/User/cvs/fileutd.h	f	0	1	1000	1000	644			16	0	
file://localhost	/home/User/dir space	d	0	0	1000	1000	755			17	0	
file://localhost	/home/User/dir space/file space	f	0	1	1000	1000	644			18	0	
file://localhost	/home/User/test space	f	0	1	1000	1000	644			23	0	
file://localhost	/home/User/testdir	d	0	0	1000	1000	755			24	0	
file://localhost	/home/User/testfile	f	13	1	1000	1000	644			25	0	
file://localhost	/home/User/testfile~	f	0	1	1000	1000	644			26	0	
file://localhost	/home/User/testpipe	p	0	1	1000	1000	644			28	0	
Removed list: 5 element(s):
file://localhost	/home/User/subdir	d	0	0	1000	1000	755			19	29	
file://localhost	/home/User/subdir/testfile	f	12	1	1000	1000	644			20	30	
file://localhost	/home/User/subdir/testfile1	f	0	1	1000	1000	644			21	31	
file://localhost	/home/User/subdir/testfile2	f	12	1	1000	1000	644			22	32	
file://localhost	/home/User/testlink	l	8	0	1000	1000	777	testfile		27	33	
as previous with CVS parser
Directory should be under CVS control: test1/cvs/dirbad
 ---> Removed: cvs/dirbad/fileoth
 ---> Removed: cvs/dirbad/fileutd
 ---> Removed: cvs/diroth
 ---> Removed: cvs/dirutd/fileoth
 ---> Removed: cvs/fileoth
Active list:  18 element(s):
file://localhost	/home/User/cvs	d	0	0	1000	1000	755			1	0	
file://localhost	/home/User/cvs/CVS	d	0	0	1000	1000	755			2	0	
file://localhost	/home/User/cvs/CVS/Entries	f	141	1	1000	1000	644			3	0	
file://localhost	/home/User/cvs/dirbad	d	0	0	1000	1000	755			4	0	
file://localhost	/home/User/cvs/dirutd	d	0	0	1000	1000	755			8	0	
file://localhost	/home/User/cvs/dirutd/CVS	d	0	0	1000	1000	755			9	0	
file://localhost	/home/User/cvs/dirutd/CVS/Entries	f	42	1	1000	1000	644			10	0	
file://localhost	/home/User/cvs/dirutd/fileutd	f	0	1	1000	1000	644			12	0	
file://localhost	/home/User/cvs/filemod.o	f	0	1	1000	1000	644			13	0	
file://localhost	/home/User/cvs/filenew.c	f	0	1	1000	1000	644			14	0	
file://localhost	/home/User/cvs/fileutd.h	f	0	1	1000	1000	644			16	0	
file://localhost	/home/User/dir space	d	0	0	1000	1000	755			17	0	
file://localhost	/home/User/dir space/file space	f	0	1	1000	1000	644			18	0	
file://localhost	/home/User/test space	f	0	1	1000	1000	644			23	0	
file://localhost	/home/User/testdir	d	0	0	1000	1000	755			24	0	
file://localhost	/home/User/testfile	f	13	1	1000	1000	644			25	0	
file://localhost	/home/User/testfile~	f	0	1	1000	1000	644			26	0	
file://localhost	/home/User/testpipe	p	0	1	1000	1000	644			28	0	
Removed list: 10 element(s):
file://localhost	/home/User/subdir	d	0	0	1000	1000	755			19	29	
file://localhost	/home/User/subdir/testfile	f	12	1	1000	1000	644			20	30	
file://localhost	/home/User/subdir/testfile1	f	0	1	1000	1000	644			21	31	
file://localhost	/home/User/subdir/testfile2	f	12	1	1000	1000	644			22	32	
file://localhost	/home/User/testlink	l	8	0	1000	1000	777	testfile		27	33	
file://localhost	/home/User/cvs/dirbad/fileoth	f	0	1	1000	1000	644			5	34	
file://localhost	/home/User/cvs/dirbad/fileutd	f	0	1	1000	1000	644			6	35	
file://localhost	/home/User/cvs/diroth	d	0	0	1000	1000	755			7	36	
file://localhost	/home/User/cvs/dirutd/fileoth	f	0	1	1000	1000	644			11	37	
file://localhost	/home/User/cvs/fileoth	f	0	1	1000	1000	644			15	38	
as previous
Directory should be under CVS control: test1/cvs/dirbad
Active list:  18 element(s):
file://localhost	/home/User/cvs	d	0	0	1000	1000	755			1	0	
file://localhost	/home/User/cvs/CVS	d	0	0	1000	1000	755			2	0	
file://localhost	/home/User/cvs/CVS/Entries	f	141	1	1000	1000	644			3	0	
file://localhost	/home/User/cvs/dirbad	d	0	0	1000	1000	755			4	0	
file://localhost	/home/User/cvs/dirutd	d	0	0	1000	1000	755			8	0	
file://localhost	/home/User/cvs/dirutd/CVS	d	0	0	1000	1000	755			9	0	
file://localhost	/home/User/cvs/dirutd/CVS/Entries	f	42	1	1000	1000	644			10	0	
file://localhost	/home/User/cvs/dirutd/fileutd	f	0	1	1000	1000	644			12	0	
file://localhost	/home/User/cvs/filemod.o	f	0	1	1000	1000	644			13	0	
file://localhost	/home/User/cvs/filenew.c	f	0	1	1000	1000	644			14	0	
file://localhost	/home/User/cvs/fileutd.h	f	0	1	1000	1000	644			16	0	
file://localhost	/home/User/dir space	d	0	0	1000	1000	755			17	0	
file://localhost	/home/User/dir space/file space	f	0	1	1000	1000	644			18	0	
file://localhost	/home/User/test space	f	0	1	1000	1000	644			23	0	
file://localhost	/home/User/testdir	d	0	0	1000	1000	755			24	0	
file://localhost	/home/User/testfile	f	13	1	1000	1000	644			25	0	
file://localhost	/home/User/testfile~	f	0	1	1000	1000	644			26	0	
file://localhost	/home/User/testpipe	p	0	1	1000	1000	644			28	0	
Removed list: 10 element(s):
file://localhost	/home/User/subdir	d	0	0	1000	1000	755			19	29	
file://localhost	/home/User/subdir/testfile	f	12	1	1000	1000	644			20	30	
file://localhost	/home/User/subdir/testfile1	f	0	1	1000	1000	644			21	31	
file://localhost	/home/User/subdir/testfile2	f	12	1	1000	1000	644			22	32	
file://localhost	/home/User/testlink	l	8	0	1000	1000	777	testfile		27	33	
file://localhost	/home/User/cvs/dirbad/fileoth	f	0	1	1000	1000	644			5	34	
file://localhost	/home/User/cvs/dirbad/fileutd	f	0	1	1000	1000	644			6	35	
file://localhost	/home/User/cvs/diroth	d	0	0	1000	1000	755			7	36	
file://localhost	/home/User/cvs/dirutd/fileoth	f	0	1	1000	1000	644			11	37	
file://localhost	/home/User/cvs/fileoth	f	0	1	1000	1000	644			15	38	
as previous with cvs/dirutd in ignore list
Directory should be under CVS control: test1/cvs/dirbad
 ---> Removed: cvs/dirutd
Active list:  14 element(s):
file://localhost	/home/User/cvs	d	0	0	1000	1000	755			1	0	
file://localhost	/home/User/cvs/CVS	d	0	0	1000	1000	755			2	0	
file://localhost	/home/User/cvs/CVS/Entries	f	141	1	1000	1000	644			3	0	
file://localhost	/home/User/cvs/dirbad	d	0	0	1000	1000	755			4	0	
file://localhost	/home/User/cvs/filemod.o	f	0	1	1000	1000	644			13	0	
file://localhost	/home/User/cvs/filenew.c	f	0	1	1000	1000	644			14	0	
file://localhost	/home/User/cvs/fileutd.h	f	0	1	1000	1000	644			16	0	
file://localhost	/home/User/dir space	d	0	0	1000	1000	755			17	0	
file://localhost	/home/User/dir space/file space	f	0	1	1000	1000	644			18	0	
file://localhost	/home/User/test space	f	0	1	1000	1000	644			23	0	
file://localhost	/home/User/testdir	d	0	0	1000	1000	755			24	0	
file://localhost	/home/User/testfile	f	13	1	1000	1000	644			25	0	
file://localhost	/home/User/testfile~	f	0	1	1000	1000	644			26	0	
file://localhost	/home/User/testpipe	p	0	1	1000	1000	644			28	0	
Removed list: 14 element(s):
file://localhost	/home/User/subdir	d	0	0	1000	1000	755			19	29	
file://localhost	/home/User/subdir/testfile	f	12	1	1000	1000	644			20	30	
file://localhost	/home/User/subdir/testfile1	f	0	1	1000	1000	644			21	31	
file://localhost	/home/User/subdir/testfile2	f	12	1	1000	1000	644			22	32	
file://localhost	/home/User/testlink	l	8	0	1000	1000	777	testfile		27	33	
file://localhost	/home/User/cvs/dirbad/fileoth	f	0	1	1000	1000	644			5	34	
file://localhost	/home/User/cvs/dirbad/fileutd	f	0	1	1000	1000	644			6	35	
file://localhost	/home/User/cvs/diroth	d	0	0	1000	1000	755			7	36	
file://localhost	/home/User/cvs/dirutd/fileoth	f	0	1	1000	1000	644			11	37	
file://localhost	/home/User/cvs/fileoth	f	0	1	1000	1000	644			15	38	
file://localhost	/home/User/cvs/dirutd	d	0	0	1000	1000	755			8	39	
file://localhost	/home/User/cvs/dirutd/CVS	d	0	0	1000	1000	755			9	40	
file://localhost	/home/User/cvs/dirutd/CVS/Entries	f	42	1	1000	1000	644			10	41	
file://localhost	/home/User/cvs/dirutd/fileutd	f	0	1	1000	1000	644			12	42	
 --> Database active items part closed (contents: 14 files)
 --> Database removed items part open (contents: 14 files)
 --> Database removed items part closed (contents: 14 files)
