
1:
3: abc

2:
3: def

3:
3: abc

4:
3: abc

5:
abc < def
abc == abc
def > abc
abc < def
def == def

6:
abc and def differ
abc and abc are equal
abc and def differ
def and def are equal

7:
6: abcdef
9: abcdefghi

Test: pathCompare
a <> a: 0
a <> b: -1
b <> a: 1
a1 <> b: -1
b <> a1: 1
a1 <> a: 1
a <> a1: -1
a/ <> a: 1
a <> a/: -1
a	 <> a/: -1
a/ <> a	 1
a	 <> a	 0
a
 <> a/: -1
a/ <> a
 1
a
 <> a
 0
a/ <> a.: -1
a. <> a/: 1
a/ <> a-: -1
a- <> a/: 1
a/ <> a/: 0
abcd <> abce, 3: 0
abcd <> abce, 4: -1
abcd <> abce, 5: -1
