clients: backup: list file not found etc/doesnotexist
mount: only root can do that
clients: backup: could not mount nfs share
mount: only root can do that
clients: backup: could not mount smb share
clients: backup: ssh protocol not supported
clients: backup: client test protocol not supported
clients: backup: client test2 protocol not supported
clients: backup: client test3 protocol not supported
clients: backup: client test4 protocol not supported
clients: backup: keyword not implemented in list file etc/localhost.list, line 3
clients: backup: keyword not implemented in list file etc/localhost.list, line 3
List 0 elements:
List 1 elements:
 file://localhost etc/doesnotexist
List 0 elements:
List 1 elements:
 nfs://myclient /home/User/devel
List 2 elements:
 nfs://myclient /home/User/devel
 smb://Myself:flesyM@myclient C:\Backup\Backup.LST
List 3 elements:
 nfs://myclient /home/User/devel
 smb://Myself:flesyM@myclient C:\Backup\Backup.LST
 ssh://otherclient /home/backup/Backup.list
List 4 elements:
 nfs://myclient /home/User/devel
 smb://Myself:flesyM@myclient C:\Backup\Backup.LST
 ssh://otherclient /home/backup/Backup.list
 client test://user@client /home/BlaH/Backup.list
List 5 elements:
 nfs://myclient /home/User/devel
 smb://Myself:flesyM@myclient C:\Backup\Backup.LST
 ssh://otherclient /home/backup/Backup.list
 client test://user@client /home/BlaH/Backup.list
 client test2://user@client /home/BlaH/Backup.list
List 6 elements:
 nfs://myclient /home/User/devel
 smb://Myself:flesyM@myclient C:\Backup\Backup.LST
 ssh://otherclient /home/backup/Backup.list
 client test://user@client /home/BlaH/Backup.list
 client test2://user@client /home/BlaH/Backup.list
 client test3://client /home/BlaH/Backup.list
List 7 elements:
 nfs://myclient /home/User/devel
 smb://Myself:flesyM@myclient C:\Backup\Backup.LST
 ssh://otherclient /home/backup/Backup.list
 client test://user@client /home/BlaH/Backup.list
 client test2://user@client /home/BlaH/Backup.list
 client test3://client /home/BlaH/Backup.list
 client test4://client /home/BlaH/Backup.list
 -> Initialized database list
 --> Issuing command: mount -t nfs -o ro,nolock myclient:/home/User/devel test_db/mount
 --> Issuing command: mount -t smbfs -o ro,nocase,username=Myself,password=flesyM //myclient/C$ test_db/mount
 -> Saving database list: 0 file(s)
 -> Loaded database list: 0 file(s)
Backup client 'localhost' using protocol 'file'
Backup path 'test'
 -> Building list of files
 -> Parsing list of files
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files
 -> Saving database list: 15 file(s)
 -> Loaded database list: 15 file(s)
Backup client 'localhost' using protocol 'file'
Backup path 'test'
 -> Building list of files
 -> Parsing list of files
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files
 -> Saving database list: 15 file(s)
