iterate_directory
List 24 elements:
 cvs
 cvs/CVS
 cvs/CVS/Entries
 cvs/dirbad
 cvs/dirbad/fileoth
 cvs/dirbad/fileutd
 cvs/diroth
 cvs/dirutd
 cvs/dirutd/CVS
 cvs/dirutd/CVS/Entries
 cvs/dirutd/fileoth
 cvs/dirutd/fileutd
 cvs/filemod.o
 cvs/filenew.c
 cvs/fileoth
 cvs/fileutd.h
 subdir
 subdir/testfile
 subdir/testfile1
 subdir/testfile2
 testdir
 testfile
 testfile~
 testlink
as previous with subdir in ignore list
List 20 elements:
 cvs
 cvs/CVS
 cvs/CVS/Entries
 cvs/dirbad
 cvs/dirbad/fileoth
 cvs/dirbad/fileutd
 cvs/diroth
 cvs/dirutd
 cvs/dirutd/CVS
 cvs/dirutd/CVS/Entries
 cvs/dirutd/fileoth
 cvs/dirutd/fileutd
 cvs/filemod.o
 cvs/filenew.c
 cvs/fileoth
 cvs/fileutd.h
 testdir
 testfile
 testfile~
 testlink
as previous with testlink in ignore list
List 19 elements:
 cvs
 cvs/CVS
 cvs/CVS/Entries
 cvs/dirbad
 cvs/dirbad/fileoth
 cvs/dirbad/fileutd
 cvs/diroth
 cvs/dirutd
 cvs/dirutd/CVS
 cvs/dirutd/CVS/Entries
 cvs/dirutd/fileoth
 cvs/dirutd/fileutd
 cvs/filemod.o
 cvs/filenew.c
 cvs/fileoth
 cvs/fileutd.h
 testdir
 testfile
 testfile~
as previous with CVS parser
List 10 elements:
 cvs
 cvs/dirbad
 cvs/dirutd
 cvs/dirutd/fileutd
 cvs/filemod.o
 cvs/filenew.c
 cvs/fileutd.h
 testdir
 testfile
 testfile~
filelist_new, as previous
List 10 elements:
 cvs
 cvs/dirbad
 cvs/dirutd
 cvs/dirutd/fileutd
 cvs/filemod.o
 cvs/filenew.c
 cvs/fileutd.h
 testdir
 testfile
 testfile~
filelist_new, as previous with ending slash
List 10 elements:
 cvs
 cvs/dirbad
 cvs/dirutd
 cvs/dirutd/fileutd
 cvs/filemod.o
 cvs/filenew.c
 cvs/fileutd.h
 testdir
 testfile
 testfile~
