List file not found etc/doesnotexist
mount: only root can do that
Protocol not supported: ssh
>List 0 client(s):
 --> Client: localhost
>List 1 client(s):
-> file://localhost etc/doesnotexist
Backup client 'localhost' using protocol 'file'
>List 0 client(s):
 --> Client: myClient
>List 1 client(s):
-> nfs://myClient /home/User/devel
 --> Client: myClient2
>List 2 client(s):
-> nfs://myClient /home/User/devel
-> smb://Myself:flesyM@myClient C:\Backup\Backup.LST
 --> Client: otherClient
>List 3 client(s):
-> nfs://myClient /home/User/devel
-> smb://Myself:flesyM@myClient C:\Backup\Backup.LST
-> ssh://otherClient c:/home/backup/Backup.list
 --> Client: Client
>List 4 client(s):
-> nfs://myClient /home/User/devel
-> smb://Myself:flesyM@myClient C:\Backup\Backup.LST
-> ssh://otherClient c:/home/backup/Backup.list
-> smb://user@Client c:/home/BlaH/Backup.list
 --> Client: Client2
>List 5 client(s):
-> nfs://myClient /home/User/devel
-> smb://Myself:flesyM@myClient C:\Backup\Backup.LST
-> ssh://otherClient c:/home/backup/Backup.list
-> smb://user@Client c:/home/BlaH/Backup.list
-> smb://user@Client c:/home/BlaH/Backup.list
 --> Client: Client3
>List 6 client(s):
-> nfs://myClient /home/User/devel
-> smb://Myself:flesyM@myClient C:\Backup\Backup.LST
-> ssh://otherClient c:/home/backup/Backup.list
-> smb://user@Client c:/home/BlaH/Backup.list
-> smb://user@Client c:/home/BlaH/Backup.list
-> smb://Client c:/home/BlaH/Backup.list
 --> Client: Client4
>List 7 client(s):
-> nfs://myClient /home/User/devel
-> smb://Myself:flesyM@myClient C:\Backup\Backup.LST
-> ssh://otherClient c:/home/backup/Backup.list
-> smb://user@Client c:/home/BlaH/Backup.list
-> smb://user@Client c:/home/BlaH/Backup.list
-> smb://Client c:/home/BlaH/Backup.list
-> smb://Client c:/home/BlaH/Backup.list
Database initialized
Client unreachable 'myClient' using protocol 'nfs'
Client unreachable 'myClient2' using protocol 'smb'
Client unreachable 'Client' using protocol 'smb'
Client unreachable 'Client2' using protocol 'smb'
Client unreachable 'Client3' using protocol 'smb'
Client unreachable 'Client4' using protocol 'smb'
Database closed (total contents: 0 file(s))
 --> Client: testhost
>List 1 client(s):
-> file://localhost etc/localhost.list
Database opened (active contents: 0 file(s))
Backup client 'testhost' using protocol 'file'
 -> Reading backup list
 --> Path: test
 --> Path: test2
Backup path 'test'
 -> Building list of files
 -> Parsing list of files
 --> Files to add: 11 (0 bytes)
 --> Done: 1/11 --> Done: 2/11 --> Done: 3/11 --> Done: 4/11 --> Done: 5/11 --> Done: 6/11 --> Done: 7/11 --> Done: 8/11 --> Done: 9/11 --> Done: 10/11 --> Done: 11/11 --> No files to remove
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files
 --> Files to add: 5 (928768 bytes)
 --> Done: 1/5 (0.0%) --> Done: 2/5 (15.7%) --> Done: 3/5 (43.6%) --> Done: 4/5 (100.0%) --> Done: 5/5 (100.0%) --> No files to remove
Database closed (total contents: 16 file(s))
 --> Client: testhost
>List 1 client(s):
-> file://localhost etc/localhost.list
Database opened (active contents: 16 file(s))
Backup client 'testhost' using protocol 'file'
 -> Reading backup list
 --> Path: test
 --> Path: test2
Backup path 'test'
 -> Building list of files
 -> Parsing list of files
 --> No files to add
 --> No files to remove
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files
 --> No files to add
 --> No files to remove
Database closed (total contents: 16 file(s))
