>List 0 client(s):
 --> Client: localhost
>List 1 client(s):
-> file://localhost etc/doesnotexist
Backup client 'localhost' using protocol 'file'
List file not found etc/doesnotexist
>List 0 client(s):
 --> Client: myClient
>List 1 client(s):
-> nfs://myClient /home/User/hbackup.list
 --> Client: myClient2
>List 2 client(s):
-> nfs://myClient /home/User/hbackup.list
-> smb://myClient C:/Backup/Backup.LST
Options: username=Myself password=flesyM
 --> Client: otherClient
>List 3 client(s):
-> nfs://myClient /home/User/hbackup.list
-> smb://myClient C:/Backup/Backup.LST
Options: username=Myself password=flesyM
-> ssh://otherClient c:/home/backup/Backup.list
 --> Client: Client
>List 4 client(s):
-> nfs://myClient /home/User/hbackup.list
-> smb://myClient C:/Backup/Backup.LST
Options: username=Myself password=flesyM
-> ssh://otherClient c:/home/backup/Backup.list
-> smb://Client c:/home/BlaH/Backup.list
Options: username=user iocharset=utf8
 --> Client: Client2
>List 5 client(s):
-> nfs://myClient /home/User/hbackup.list
-> smb://myClient C:/Backup/Backup.LST
Options: username=Myself password=flesyM
-> ssh://otherClient c:/home/backup/Backup.list
-> smb://Client c:/home/BlaH/Backup.list
Options: username=user iocharset=utf8
-> smb://Client c:/home/BlaH/Backup.list
Options: nocase username=user password=
 --> Client: Client3
>List 6 client(s):
-> nfs://myClient /home/User/hbackup.list
-> smb://myClient C:/Backup/Backup.LST
Options: username=Myself password=flesyM
-> ssh://otherClient c:/home/backup/Backup.list
-> smb://Client c:/home/BlaH/Backup.list
Options: username=user iocharset=utf8
-> smb://Client c:/home/BlaH/Backup.list
Options: nocase username=user password=
-> smb://Client c:/home/BlaH/Backup.list
Options: username=
 --> Client: Client4
>List 7 client(s):
-> nfs://myClient /home/User/hbackup.list
-> smb://myClient C:/Backup/Backup.LST
Options: username=Myself password=flesyM
-> ssh://otherClient c:/home/backup/Backup.list
-> smb://Client c:/home/BlaH/Backup.list
Options: username=user iocharset=utf8
-> smb://Client c:/home/BlaH/Backup.list
Options: nocase username=user password=
-> smb://Client c:/home/BlaH/Backup.list
Options: username=
-> smb://Client c:/home/BlaH/Backup.list
Options: username= password=
Database initialized
Client unreachable 'myClient' using protocol 'nfs'
Client unreachable 'myClient2' using protocol 'smb'
Protocol not supported: ssh
Client unreachable 'Client' using protocol 'smb'
Client unreachable 'Client2' using protocol 'smb'
Client unreachable 'Client3' using protocol 'smb'
Client unreachable 'Client4' using protocol 'smb'
Database closed (active contents: 0 files, removed contents: 0 files)
 --> Client: testhost
>List 1 client(s):
-> file://localhost etc/localhost.list
Database opened (active contents: 0 files)
Backup client 'testhost' using protocol 'file'
 -> Reading backup list file
 --> Path: test
 --> Path: test2
Backup path 'test'
 -> Building list of files
Directory should be under CVS control: test/cvs/dirbad
 -> Parsing list of files (13)
 --> Files to add: 13 (0 bytes)
 --> Done: 1/13 --> Done: 2/13 --> Done: 3/13 --> Done: 4/13 --> Done: 5/13 --> Done: 6/13 --> Done: 7/13 --> Done: 8/13 --> Done: 9/13 --> Done: 10/13 --> Done: 11/13 --> Done: 12/13 --> Done: 13/13 --> Files to remove: 0
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files (5)
 --> Files to add: 5 (928768 bytes)
 --> Done: 1/5 (0.0%) --> Done: 2/5 (15.7%) --> Done: 3/5 (43.6%) --> Done: 4/5 (100.0%) --> Done: 5/5 (100.0%) --> Files to remove: 0
Database closed (active contents: 18 files, removed contents: 0 files)
 --> Client: testhost
>List 1 client(s):
-> file://testhost etc/localhost.list
Database opened (active contents: 18 files)
Backup client 'testhost' using protocol 'file'
 -> Reading backup list file
 --> Path: test
 --> Path: test2
Backup path 'test'
 -> Building list of files
Directory should be under CVS control: test/cvs/dirbad
 -> Parsing list of files (13)
 --> Files to add: 0
 --> Files to remove: 0
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files (5)
 --> Files to add: 0
 --> Files to remove: 0
Database closed (active contents: 18 files, removed contents: 0 files)
