#!/bin/bash

# Dir names
TESTDBDIR="test_db"
TESTDIR="test"
TESTDIR2="test2"
CONFIGDIR="etc"

# Clean
rm -rf "$TESTDBDIR"
rm -rf "$TESTDIR"
rm -rf "$TESTDIR2"
rm -rf "$CONFIGDIR"

if [ "$1" == "clean" ]; then
  exit 0
fi

# Database
mkdir "$TESTDBDIR"

# Test bench
mkdir "$TESTDIR"
mkdir "$TESTDIR/testdir"
echo "Hello world!" > "$TESTDIR/testfile"
touch -d 20061022 "$TESTDIR/testfile"
touch "$TESTDIR/testfile~"
ln -s "testfile" "$TESTDIR/testlink"

# Filters test
mkdir "$TESTDIR/subdir"
echo "Hello Moon!" > "$TESTDIR/subdir/testfile"
touch "$TESTDIR/subdir/testfile1"
echo "Hello Moon!" > "$TESTDIR/subdir/testfile2"
touch "$TESTDIR/test space"
mkdir "$TESTDIR/dir space"
touch "$TESTDIR/dir space/file space"

# CVS test
CVSDIR="$TESTDIR/cvs"
mkdir "$CVSDIR"
touch "$CVSDIR/filemod.o"
touch "$CVSDIR/filenew.c"
touch "$CVSDIR/fileoth"
touch "$CVSDIR/fileutd.h"
mkdir "$CVSDIR/dirbad"
touch "$CVSDIR/dirbad/fileoth"
touch "$CVSDIR/dirbad/fileutd"
mkdir "$CVSDIR/diroth"
mkdir "$CVSDIR/dirutd"
touch "$CVSDIR/dirutd/fileoth"
touch "$CVSDIR/dirutd/fileutd"
mkdir "$CVSDIR/dirutd/CVS"
cat << EOF > "$CVSDIR/dirutd/CVS/Entries"
/fileutd/1.2/Wed Oct  4 18:04:40 2006//
D
EOF
mkdir "$CVSDIR/CVS"
cat << EOF > "$CVSDIR/CVS/Entries"
/filenew.c/0/dummy timestamp//
/filemod.o/1.1/Mon Oct  2 16:27:11 2006//
/fileutd.h/1.2/Wed Oct  4 18:04:40 2006//
D/dirbad////
D/dirutd////
EOF

# Multiple backup
mkdir "$TESTDIR2"
mkdir "$TESTDIR2/testdir"
echo "Bye bye world!" > "$TESTDIR2/testfile"
touch -t 200610221134.56 "$TESTDIR2/testfile"
dd if=/dev/zero of="$TESTDIR2/testfile~" bs=512 count=1024 2> /dev/null
ln -s "testfile" "$TESTDIR2/testlink"


# Config
mkdir "$CONFIGDIR"
cat << EOF > "$CONFIGDIR/hbackup.conf"
db "$TESTDBDIR"
client file://cbers11 "$CONFIGDIR/localhost.list"
client Smb://Myself:flesyM@myClient "C:\Backup\Backup.LST"
client sSh://otherClient /home/backup/Backup.list
EOF
cat << EOF > "$CONFIGDIR/localhost.list"
# Share test
path "test" # should work
ignore path_start subdir
ignore file/path_end ~
ignore path_end ".o"
ignore size_above 10
parser all cvs

path test2//
EOF
