 -> Reading configuration file
 --> Client: myClient
 --> Client: other
 --> Client: myhost
 --> Client: client
 -> Backing up
 --> Database initialized
 --> Database list open (contents: 0 files)
Backup client 'myhost' using protocol 'file'
 -> Reading backup list file
 --> Path: test2
 --> Path: test1
Backup path 'test1'
 --> A cvs
 --> A cvs/CVS
 --> A cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
 --> A cvs/dirutd
 --> A cvs/dirutd/CVS
 --> A cvs/dirutd/fileutd
 --> A cvs/filenew.c
 --> A cvs/fileutd.h
 --> A dir space
 --> A dir space/file space
 --> A test space
 --> A testdir
 --> A testlink
 --> A testpipe
Backup path 'test2'
 --> A testdir
 --> A testfile
 --> A testfile2
 --> A testfile~
 --> A testlink
Backup client 'myClient' using protocol 'nfs'
 -> Reading backup list file
 --> Path: /home/User/test
Backup path '/home/User/test'
Unmounted test_db/mount
 --> A File2.txt
Unmounted test_db/mount
Backup client 'client' using protocol 'smb'
 -> Reading backup list file
 --> Path: C:/Test
Backup path 'C:/Test'
 --> A File.TXT
Unmounted test_db/mount
Protocol not supported: ssh
 -> Reading configuration file
 --> Client: myClient
 --> Client: other
 --> Client: myhost
 --> Client: client
 -> Backing up
 --> Database list open (contents: 21 files)
Backup client 'myhost' using protocol 'file'
 -> Reading backup list file
 --> Path: test2
 --> Path: test1
Backup path 'test1'
Directory should be under CVS control: test1/cvs/dirbad
Backup path 'test2'
Backup client 'client' using protocol 'smb'
 -> Reading backup list file
 --> Path: C:/Test
Backup path 'C:/Test'
Unmounted test_db/mount
 -> Reading configuration file
 --> Client: myClient
 --> Client: other
 --> Client: myhost
 --> Client: client
 -> Scanning database
 --> Database list open (contents: 21 files)
 -> Scanning database
 --> Scanning database contents: 21 files
 -> Reading configuration file
 --> Client: myClient
 --> Client: other
 --> Client: myhost
 --> Client: client
 -> Checking database
 --> Database list open (contents: 21 files)
 -> Checking database
 --> Scanning database contents thoroughly: 21 files
