 -> Reading configuration file
 --> Client: myhost
 --> Client: myClient
 --> Client: client
 --> Client: other
 -> Opening database
 --> Database initialized
 --> Database active items part open (contents: 0 files)
Backup client 'myhost' using protocol 'file'
 -> Reading backup list file
 --> Path: test1
 --> Path: test2
Backup path 'test1'
 --> A cvs
 --> A cvs/CVS
 --> A cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
 --> A cvs/dirutd
 --> A cvs/dirutd/CVS
 --> A cvs/dirutd/fileutd
 --> A cvs/filenew.c
 --> A cvs/fileutd.h
 --> A dir space
 --> A dir space/file space
 --> A test space
 --> A testdir
 --> A testlink
 --> A testpipe
Backup path 'test2'
 --> A testdir
 --> A testfile
 --> A testfile2
 --> A testfile~
 --> A testlink
Backup client 'myClient' using protocol 'nfs'
 -> Reading backup list file
 --> Path: /home/User/test
Backup path '/home/User/test'
Unmounted test_db/mount
 --> A File2.txt
Unmounted test_db/mount
Backup client 'client' using protocol 'smb'
 -> Reading backup list file
 --> Path: C:/Test
Backup path 'C:/Test'
 --> A File.TXT
Unmounted test_db/mount
Protocol not supported: ssh
 --> Database active items part closed (contents: 21 files)
 --> Database removed items part open (contents: 0 files)
Expire path 'test1'
 -> Removing expired records
 --> Expired data: 0
 -> Closing database
 --> Database removed items part closed (contents: 0 files)
 -> Reading configuration file
 --> Client: myhost
 --> Client: myClient
 --> Client: client
 --> Client: other
 -> Opening database
Reading version 1 lists
 --> Database active items part open (contents: 21 files)
Backup client 'myhost' using protocol 'file'
 -> Reading backup list file
 --> Path: test1
 --> Path: test2
Backup path 'test1'
Directory should be under CVS control: test1/cvs/dirbad
Backup path 'test2'
Backup client 'client' using protocol 'smb'
 -> Reading backup list file
 --> Path: C:/Test
Backup path 'C:/Test'
Unmounted test_db/mount
 --> Database active items part closed (contents: 21 files)
Reading version 1 lists
 --> Database removed items part open (contents: 0 files)
Expire path 'test1'
 -> Removing expired records
 --> Expired data: 0
 -> Closing database
 --> Database removed items part closed (contents: 0 files)
 -> Reading configuration file
 --> Client: myhost
 --> Client: myClient
 --> Client: client
 --> Client: other
 -> Opening database
Reading version 1 lists
 --> Database active items part open (contents: 21 files)
 -> Scanning database
 --> Scanning database contents: 21 files
 -> Closing database
 --> Database active items part closed (contents: 21 files)
 -> Reading configuration file
 --> Client: myhost
 --> Client: myClient
 --> Client: client
 --> Client: other
 -> Opening database
Reading version 1 lists
 --> Database active items part open (contents: 21 files)
 -> Checking database
 --> Scanning database contents thoroughly: 21 files
 -> Closing database
 --> Database active items part closed (contents: 21 files)
 -> Reading configuration file
 --> Client: myhost
 --> Client: myClient
 --> Client: client
 --> Client: other
 -> Opening database
Reading version 1 lists
 --> Database active items part open (contents: 20 files)
 -> Updating database format
 --> Database active items part closed (contents: 20 files)
Reading version 1 lists
 --> Database removed items part open (contents: 6 files)
 -> Closing database
 --> Database removed items part closed (contents: 6 files)

# version 1
file://client
	/home/user2/testdir
		18	d	0	0	1000	1000	755	
	/home/user2/testfile
		19	f	145408	1161527696	1000	1000	644	3d546a1ce46c6ae10ad34ab8a81c542e-0	
	/home/user2/testfile2
		20	f	259072	1187315785	1000	1000	644	fb00cd74a5f35e89a7fbdd3c1d05375a-0	
	/home/user2/testlink
		21	l	8	1187315785	1000	1000	777	testfile	
file://host
	/home/user/cvs
		2	d	0	0	1000	1000	755	
	/home/user/cvs/CVS
		3	d	0	0	1000	1000	755	
	/home/user/cvs/CVS/Entries
		4	f	141	1187315785	1000	1000	644	63b52e85e7a255c09df5cca819b74a88-0	
	/home/user/cvs/dirbad
		5	d	0	0	1000	1000	755	
	/home/user/cvs/dirutd
		6	d	0	0	1000	1000	755	
	/home/user/cvs/dirutd/CVS
		7	d	0	0	1000	1000	755	
	/home/user/cvs/dirutd/CVS/Entries
		8	f	42	1187315785	1000	1000	644	5252f242d27b8c2c9fdbdcbb33545d07-0	
	/home/user/cvs/dirutd/fileutd
		9	f	0	1187315785	1000	1000	644	d41d8cd98f00b204e9800998ecf8427e-0	
	/home/user/cvs/filenew.c
		10	f	0	1187315785	1000	1000	644	d41d8cd98f00b204e9800998ecf8427e-0	
	/home/user/cvs/fileutd.h
		11	f	0	1187315785	1000	1000	644	d41d8cd98f00b204e9800998ecf8427e-0	
	/home/user/dir space
		12	d	0	0	1000	1000	755	
	/home/user/dir space/file space
		13	f	0	1187315785	1000	1000	644	d41d8cd98f00b204e9800998ecf8427e-0	
	/home/user/test space
		14	f	0	1187315785	1000	1000	644	d41d8cd98f00b204e9800998ecf8427e-0	
	/home/user/testdir
		15	d	0	0	1000	1000	755	
	/home/user/testfile
		16	f	13	1161486000	1000	1000	644	59ca0efa9f5633cb0371bbc0355478d8-0	
	/home/user/testlink
		17	l	8	1187315785	1000	1000	777	testfile	
#

# version 1
file://host
	/home/user/cvs/dirutd/CVS/Entries
		22	f	42	1187315785	1000	1000	775	5252f242d27b8c2c9fdbdcbb33545d07-0	
		30	-	
	/home/user/cvs/dirutd/fileutd
		9	f	0	1187315785	1000	1000	644	d41d8cd98f00b204e9800998ecf8427e-0	
		33	-	
	/home/user/dir space/file space
		13	f	0	1187315785	1000	1000	644	d41d8cd98f00b204e9800998ecf8427e-0	
		28	-	
	/home/user/testdir
		15	d	0	0	1000	1000	755	
		24	d	0	0	1000	1000	775	
		32	-	
	/home/user/testfile
		16	f	13	1161486000	1000	1000	644		
		27	-	
#
