 -> Reading configuration file
 --> Client: cbers11
 --> Client: client
 --> Client: other
 -> Opening database
 --> Database initialized
 --> Database active items part open (contents: 0 files)
Backup client 'cbers11' using protocol 'file'
 -> Reading backup list file
 --> Path: test
 --> Path: test2
Backup path 'test'
 -> Building list of files
Directory should be under CVS control: test/cvs/dirbad
 -> Parsing list of files (13)
 --> Files to add: 13 (0 bytes)
 --> Done: 1/13 --> Done: 2/13 --> Done: 3/13 --> Done: 4/13 --> Done: 5/13 --> Done: 6/13 --> Done: 7/13 --> Done: 8/13 --> Done: 9/13 --> Done: 10/13 --> Done: 11/13 --> Done: 12/13 --> Done: 13/13
 --> Files to remove: 0
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files (5)
 --> Files to add: 5 (928768 bytes)
 --> Done: 1/5 (0.0%) --> Done: 2/5 (15.7%) --> Done: 3/5 (43.6%) --> Done: 4/5 (100.0%) --> Done: 5/5 (100.0%)
 --> Files to remove: 0
Client unreachable 'client' using protocol 'smb' (Connection timed out)
Protocol not supported: ssh
 --> Database active items part closed (contents: 18 files)
 --> Database removed items part open (contents: 0 files)
Expire path 'test'
 -> Removing expired records
 --> Expired data: 0
 -> Closing database
 --> Database removed items part closed (contents: 0 files)
 -> Reading configuration file
 --> Client: cbers11
 --> Client: client
 --> Client: other
 -> Opening database
 --> Database active items part open (contents: 18 files)
Backup client 'cbers11' using protocol 'file'
 -> Reading backup list file
 --> Path: test
 --> Path: test2
Backup path 'test'
 -> Building list of files
Directory should be under CVS control: test/cvs/dirbad
 -> Parsing list of files (13)
 --> Files to add: 0
 --> Files to remove: 0
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files (5)
 --> Files to add: 0
 --> Files to remove: 0
Client unreachable 'client' using protocol 'smb' (Connection timed out)
 --> Database active items part closed (contents: 18 files)
 --> Database removed items part open (contents: 0 files)
Expire path 'test'
 -> Removing expired records
 --> Expired data: 0
 -> Closing database
 --> Database removed items part closed (contents: 0 files)
 -> Reading configuration file
 --> Client: cbers11
 --> Client: client
 --> Client: other
 -> Opening database
 --> Database active items part open (contents: 18 files)
 -> Scanning database
 --> Scanning database contents: 18 files
 --> Database active items part closed (contents: 18 files)
 --> Database removed items part open (contents: 0 files)
 -> Removing expired records
 --> Expired data: 0
 -> Closing database
 --> Database removed items part closed (contents: 0 files)
 -> Reading configuration file
 --> Client: cbers11
 --> Client: client
 --> Client: other
 -> Opening database
 --> Database active items part open (contents: 18 files)
 -> Checking database
 --> Scanning database contents thoroughly: 18 files
 --> Database active items part closed (contents: 18 files)
 --> Database removed items part open (contents: 0 files)
 -> Removing expired records
 --> Expired data: 0
 -> Closing database
 --> Database removed items part closed (contents: 0 files)
