 -> Reading configuration file
 --> Client: myhost
 --> Client: myClient
 --> Client: client
 --> Client: other
 -> Opening database
 --> Database initialized
 --> Database active items part open (contents: 0 files)
Backup client 'myhost' using protocol 'file'
 -> Reading backup list file
 --> Path: test1
 --> Path: test2
Backup path 'test1'
 -> Building list of files
Directory should be under CVS control: test1/cvs/dirbad
 -> Parsing list of files (13)
 --> Files to add: 13 (0 bytes)
 --> Done: 1/13 --> Done: 2/13 --> Done: 3/13 --> Done: 4/13 --> Done: 5/13 --> Done: 6/13 --> Done: 7/13 --> Done: 8/13 --> Done: 9/13 --> Done: 10/13 --> Done: 11/13 --> Done: 12/13 --> Done: 13/13
 --> Files to remove: 0
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files (5)
 --> Files to add: 5 (928768 bytes)
 --> Done: 1/5 (0.0%) --> Done: 2/5 (15.7%) --> Done: 3/5 (43.6%) --> Done: 4/5 (100.0%) --> Done: 5/5 (100.0%)
 --> Files to remove: 0
Backup client 'myClient' using protocol 'nfs'
 -> Reading backup list file
 --> Path: /home/User/test
Backup path '/home/User/test'
 -> Building list of files
Unmounted test_db/mount
 -> Parsing list of files (1)
 --> Files to add: 1 (0 bytes)
 --> Done: 1/1
 --> Files to remove: 0
Unmounted test_db/mount
Backup client 'client' using protocol 'smb'
 -> Reading backup list file
 --> Path: C:/Test
Backup path 'C:/Test'
 -> Building list of files
 -> Parsing list of files (1)
 --> Files to add: 1 (0 bytes)
 --> Done: 1/1
 --> Files to remove: 0
Unmounted test_db/mount
Protocol not supported: ssh
 --> Database active items part closed (contents: 20 files)
 --> Database removed items part open (contents: 0 files)
Expire path 'test1'
 -> Removing expired records
 --> Expired data: 0
 -> Closing database
 --> Database removed items part closed (contents: 0 files)
 -> Reading configuration file
 --> Client: myhost
 --> Client: myClient
 --> Client: client
 --> Client: other
 -> Opening database
 --> Database active items part open (contents: 20 files)
Backup client 'myhost' using protocol 'file'
 -> Reading backup list file
 --> Path: test1
 --> Path: test2
Backup path 'test1'
 -> Building list of files
Directory should be under CVS control: test1/cvs/dirbad
 -> Parsing list of files (13)
 --> Files to add: 0
 --> Files to remove: 0
Backup path 'test2'
 -> Building list of files
 -> Parsing list of files (5)
 --> Files to add: 0
 --> Files to remove: 0
Backup client 'client' using protocol 'smb'
 -> Reading backup list file
 --> Path: C:/Test
Backup path 'C:/Test'
 -> Building list of files
 -> Parsing list of files (1)
 --> Files to add: 0
 --> Files to remove: 0
Unmounted test_db/mount
 --> Database active items part closed (contents: 20 files)
 --> Database removed items part open (contents: 0 files)
Expire path 'test1'
 -> Removing expired records
 --> Expired data: 0
 -> Closing database
 --> Database removed items part closed (contents: 0 files)
 -> Reading configuration file
 --> Client: myhost
 --> Client: myClient
 --> Client: client
 --> Client: other
 -> Opening database
 --> Database active items part open (contents: 20 files)
 -> Scanning database
 --> Scanning database contents: 20 files
 --> Database active items part closed (contents: 20 files)
 --> Database removed items part open (contents: 0 files)
 -> Removing expired records
 --> Expired data: 0
 -> Closing database
 --> Database removed items part closed (contents: 0 files)
 -> Reading configuration file
 --> Client: myhost
 --> Client: myClient
 --> Client: client
 --> Client: other
 -> Opening database
 --> Database active items part open (contents: 20 files)
 -> Checking database
 --> Scanning database contents thoroughly: 20 files
 --> Database active items part closed (contents: 20 files)
 --> Database removed items part open (contents: 0 files)
 -> Removing expired records
 --> Expired data: 0
 -> Closing database
 --> Database removed items part closed (contents: 0 files)
