 --> Database initialized
 --> Database active items part open (contents: 0 files)

Test: getdir
Check test_db/data dir: 0
febatest1 status: 0, getdir_path: test_db/data/fe/ba/test1
fe98test2 status: 0, getdir_path: test_db/data/fe/98/test2
fe98test3 status: 1, getdir_path: test_db/data/fe/98/test3
fetest4 status: 1, getdir_path: test_db/data/fe/te/st4
fedc76test5 status: 1, getdir_path: test_db/data/fe/dc/76/test5
fedc76test6 status: 1, getdir_path: test_db/data/fe/dc/76/test6
fedc76test6 status: 0, getdir_path: test_db/data/fe/dc/76/test6

Test: write and read back
59ca0efa9f5633cb0371bbc0355478d8-0  test1/testfile
59ca0efa9f5633cb0371bbc0355478d8-0  test_db/blah
Active list: 0 element(s):
Removed list: 0 element(s):
 --> Database active items part closed (contents: 0 files)
Reading version 1 lists
 --> Database active items part open (contents: 0 files)
Active list: 0 element(s):
Removed list: 0 element(s):
List select test
Got 0 elements
Got 0 elements
Active list: 0 element(s):
Removed list: 0 element(s):
 --> Database active items part closed (contents: 0 files)
Reading version 1 lists
 --> Database active items part open (contents: 0 files)
 --> Scanning database contents: 0 files
 --> Database active items part closed (contents: 0 files)
Reading version 1 lists
 --> Database active items part open (contents: 0 files)
 --> Scanning database contents thoroughly: 0 files
 --> Database active items part closed (contents: 0 files)
Reading version 1 lists
 --> Database active items part open (contents: 0 files)
 --> Scanning database contents: 0 files
 --> Database active items part closed (contents: 0 files)
Reading version 1 lists
 --> Database active items part open (contents: 0 files)
 --> Scanning database contents thoroughly: 0 files
 --> Database active items part closed (contents: 0 files)
Reading version 1 lists
 --> Database active items part open (contents: 0 files)
 --> Scanning database contents thoroughly: 0 files
 --> Database active items part closed (contents: 0 files)
Reading version 1 lists
 --> Database active items part open (contents: 0 files)
Active list: 0 element(s):
Removed list: 0 element(s):
Active list: 0 element(s):
Removed list: 0 element(s):
Active list: 0 element(s):
Removed list: 0 element(s):
 --> Database active items part closed (contents: 0 files)
Reading version 1 lists
 --> Database active items part open (contents: 0 files)
Active list: 0 element(s):
Removed list: 0 element(s):
Active list: 0 element(s):
Removed list: 0 element(s):
Active list: 0 element(s):
Removed list: 0 element(s):
 --> Database active items part closed (contents: 0 files)
Reading version 1 lists
 --> Database active items part open (contents: 0 files)
Active list: 0 element(s):
Removed list: 0 element(s):
Active list: 0 element(s):
Removed list: 0 element(s):
 --> Database active items part closed (contents: 0 files)
Reading version 1 lists
 --> Database active items part open (contents: 0 files)
Active list: 0 element(s):
Removed list: 0 element(s):
Expiration test
db: expiration module not initialised
db: expiration module not initialised
Modified removed list: 0 element(s):
 --> Database active items part closed (contents: 0 files)
Reading version 1 lists
 --> Database removed items part open (contents: 0 files)
 -> Removing expired records
 --> Expired data: 0
 --> Database removed items part closed (contents: 0 files)
List cannot be saved
Reading version 1 lists
 --> Database active items part open (contents: 0 files)
dblist: failed to save active items list
Error: Permission denied
List cannot be read
dblist: load: active: Permission denied
dblist: failed to load active items list
Error: Permission denied
List is garbaged
Reading version 1 lists
 --> Database active items part open (contents: 0 files)
 --> Database active items part closed (contents: 0 files)
List is gone
db: open: active files list not accessible: no backup accessible, aborting
Error: No such file or directory
