Tools Test

Test: zcopy
In: 10485760 bytes, checksum: f1c9645dbc14efddc7d8a322685f26eb
Out: 10208 bytes, checksum: b7350db49d036137b2ef752a82145e91
In: 10485760 bytes, checksum: f1c9645dbc14efddc7d8a322685f26eb
Out: 10485760 bytes, checksum: f1c9645dbc14efddc7d8a322685f26eb

Test: file read
read size: 10485760 (10485760 -> 10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb

Test: file copy (read + write)
read size: 10485760 (10485760 -> 10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb
write size: 10485760 (10485760 -> 10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb

Test: file compress (read + compress write)
read size: 10485760 (10485760 -> 10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb
write size: 10208 (10485760 -> 10208), checksum: b7350db49d036137b2ef752a82145e91

Test: file uncompress (uncompress read + write)
read size: 10485760 (10208 -> 10485760), checksum: b7350db49d036137b2ef752a82145e91
write size: 10485760 (10485760 -> 10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb

Test: file compress (read + compress write)
read size: 10485760 (10485760 -> 10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb
write size: 10208 (10485760 -> 10208), checksum: b7350db49d036137b2ef752a82145e91

Test: file recompress (uncompress read + compress write), no closing
read size: 10485760 (10208 -> 10485760), checksum: b7350db49d036137b2ef752a82145e91
write size: 10208 (10485760 -> 10208), checksum: b7350db49d036137b2ef752a82145e91

Test: typeLetter
File   : f
Dir    : d
Char   : c
Block  : b
FIFO   : p
Link   : l
Socket : s
Zero   : !
Unknown: ?

Test: typeMode
File   : 0100000
Dir    : 0040000
Char   : 0020000
Block  : 0060000
FIFO   : 0010000
Link   : 0120000
Socket : 0140000
Unknown: 0000000

metadata
Line: test1/testfile	f	13	1	1000	1000	644	
 * type: 0x00008000
 * mtime (local): 2006-10-22  0:00:00

line constructor
Line: test1/testlink	l	8	1	1000	1000	777	testfile
Line: test1/testlink	l	8	1	1000	1000	777	testfile

readline
readline(a): 0
a

readline( 	a 	b): 0
a
b

readline(	 ab): 0
ab

readline(	 ab cd): 0
ab
cd

readline(	 ab cd	ef # blah): 0
ab
cd
ef

readline(	 'ab' 'cd'	'ef' # blah): 0
ab
cd
ef

readline(	 "ab" 'cd'	"ef" # blah): 0
ab
cd
ef

readline(	 ab cd	ef 'gh ij	kl' "mn op	qr" 	# blah): 0
ab
cd
ef
gh ij	kl
mn op	qr

readline(	 ab cd	ef 'gh "ij\'	kl' "mn 'op\"	qr" 	# blah): 0
ab
cd
ef
gh "ij'	kl
mn 'op"	qr

readline(	 a\b cd	ef 'g\h "ij\'	kl' "m\n 'op\"	qr" 	# blah): 0
a\b
cd
ef
g\h "ij'	kl
m\n 'op"	qr

readline(	 a\b cd	ef 'g\h "ij\'	kl): 1
a\b
cd
ef
g\h "ij'	kl

readline(	 a\b cd	ef 'g\h "ij\'	kl' "m\n 'op\"	qr): 1
a\b
cd
ef
g\h "ij'	kl
m\n 'op"	qr

Name: testfile, type = f, mtime = 1, size = 13, uid = 1, gid = 1, mode = 420
Name: testlink, type = l, mtime = 0, size = 8, uid = 1, gid = 1, mode = 511, link = testfile
Name: testdir, type = d, mtime = 0, size = 0, uid = 1, gid = 1, mode = 493
Listing 0 entries:
Name: subdir, type = d, mtime = 0, size = 0, uid = 1, gid = 1, mode = 493
Listing 3 entries:
 -> name: testfile
 -> name: testfile1
 -> name: testfile2

Validity tests
File is file? 1
File is dir? 0
File is link? 0
Dir is file? 0
Dir is dir? 1
Dir is link? 0
Link is file? 0
Link is dir? 0
Link is link? 1

Creation tests
File is file? 0
File is dir? 0
File is link? 0
Dir is file? 0
Dir is dir? 0
Dir is link? 0
Link is file? 0
Link is dir? 0
Link is link? 0
Create
File is file? 1
File is dir? 0
File is link? 0
Dir is file? 0
Dir is dir? 1
Dir is link? 0
Link is file? 0
Link is dir? 0
Link is link? 0
Create again
File is file? 1
File is dir? 0
File is link? 0
Dir is file? 0
Dir is dir? 1
Dir is link? 0
Link is file? 0
Link is dir? 0
Link is link? 0
