Conditions test
filter_path_check
match 2.1
filter_path_start_check
match 3.1
filter_path_end_check
match 4.1
filter_path_regexp_check
match 5.1

Match function test
Matching 4000
Not matching 6000

Simple rules test
>List 1 rule(s):
-> List 1 condition(s)
--> ^to a.*\.txt 4
>List 2 rule(s):
-> List 1 condition(s)
--> ^to a.*\.txt 4
-> List 1 condition(s)
--> ^to a.*\.t.t 4
Not matching 3
Not matching +1
Not matching +2
Not matching +3
>List 1 rule(s):
-> List 1 condition(s)
--> ^to a.*\.txt 4
>List 2 rule(s):
-> List 1 condition(s)
--> ^to a.*\.txt 4
-> List 1 condition(s)
--> ^to a.*\.t.t 4
Not matching +3
Not matching 3
Not matching 0
Not matching 1000
Not matching 1000000
>List 1 rule(s):
-> List 1 condition(s)
--> 500 6
Matching 0
Not matching 1000
Not matching 1000000
>List 2 rule(s):
-> List 1 condition(s)
--> 500 6
-> List 1 condition(s)
--> 5000 5
Matching 0
Not matching 1000
Matching 1000000

Complex rules test
>List 0 rule(s):
>List 1 rule(s):
-> List 1 condition(s)
--> 500 6
>List 1 rule(s):
-> List 2 condition(s)
--> 500 6
--> 400 5
Not matching 600
Matching 500
Matching 450
Matching 400
Not matching 300
